// <auto-generated />
using EmployeeBenefits.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EmployeeBenefits.Migrations
{
    [DbContext(typeof(EmployeeBenefitsContext))]
    partial class EmployeeBenefitsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeBenefits.Models.Dependent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BaseAnnualCostOfBenefits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("EmployeeBenefits.Models.Discount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("Amount");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OptionalOperand");

                    b.HasKey("ID");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("EmployeeBenefits.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BaseAnnualCostOfBenefits");

                    b.Property<decimal>("CompensationPerPaycheck");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeBenefits.Models.EmployeeDependent", b =>
                {
                    b.Property<int>("EmployeeId");

                    b.Property<int>("DependentId");

                    b.HasKey("EmployeeId", "DependentId");

                    b.HasIndex("DependentId");

                    b.ToTable("EmployeeDependents");
                });

            modelBuilder.Entity("EmployeeBenefits.Models.EmployeeDependent", b =>
                {
                    b.HasOne("EmployeeBenefits.Models.Dependent", "Dependent")
                        .WithMany("EmployeeDependents")
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmployeeBenefits.Models.Employee", "Employee")
                        .WithMany("EmployeeDependents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
